apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: parent-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/konka-devops-lab/k8s-administration.git
        revision: main
        files:
          - path: namespaces/*.yaml
          - path: rbac/*.yaml
          - path: storage-classes/*.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/konka-devops-lab/k8s-administration.git
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true